import type { Config, HoodRollerConfig, WheelConfig } from "../physics/types";
import { deg, inch, inertiaImperial, rpm } from "../utils/units";
import { fieldConfig } from "../field/fieldConfig";
const wheel = (
  diameter: number,
  omega: number,
  mass: number | null = null,
  inertia: number | null = null,
): WheelConfig => ({
  diameter,
  omega,
  mass,
  inertia,
  inertiaMode: inertia === null ? "unknown" : "custom",
  ratio: 1,
});
const sushiWheel = (
  angle: number,
  centerX: number,
  contactStart: number,
  contactEnd: number,
): HoodRollerConfig => ({
  ...wheel(inch, rpm(1450 * 3.75)),
  ratio: 3.75,
  angle,
  radius: inch / 2,
  // Nominal center is tangent to POLLEN; global/per-roller compression moves it toward the path.
  center: [centerX, (2.8 * inch) / 2 + inch / 2],
  compression: 0,
  contactStart,
  contactEnd,
});

export const current: Config = {
  version: 1,
  name: "96mm Rhino + 3× Sushi Hood",
  calibrated: false,
  robot: {
    x: -1.15,
    y: -1.1,
    heading: deg(40),
    turretYaw: deg(4),
    turretCenter: [0, 0, 0],
    exitOffset: [0.12, 0, 0.347],
    width: 0.38,
    length: 0.4,
    velocity: [0, 0, 0],
    inheritVelocity: false,
  },
  shooter: {
    mode: "physical",
    topology: "powered",
    primary: wheel(0.096, rpm(1450)),
    secondary: sushiWheel((-20 * Math.PI) / 180, 0.025, 0, 0.06),
    rollers: [
      sushiWheel(0, 0.07, 0.025, 0.105),
      sushiWheel((20 * Math.PI) / 180, 0.115, 0.07, 0.15),
    ],
    link: "gear",
    surfaceRatio: 3.75,
    hoodAngle: deg(65),
    hoodMin: deg(35),
    hoodMax: deg(85),
    hoodOffset: 0,
    hoodStart: deg(-40),
    hoodEnd: deg(70),
    hoodRadius: 0.078,
    compression: 0.008,
    friction: 0.65,
    ballStiffness: 4500,
    wheelStiffness: 9000,
    normalModel: "linear",
    forceCurve: [
      [0, 0],
      [0.004, 12],
      [0.008, 24],
      [0.012, 40],
    ],
    hysteresis: 0.12,
    contactStep: 0.0001,
    maxContactTime: 0.25,
    transfer: 1,
    flywheel: wheel(0.1016, 0, 0, 0),
    flywheelEnabled: false,
    effectiveInertia: 0.264 * inertiaImperial,
    motor: {
      count: 2,
      name: "Uncharacterized motor (editable)",
      efficiency: 0.7,
      reduction: 2.42,
      voltage: 10,
      batteryResistance: 0.015,
      statorLimit: 100,
      supplyLimit: 10,
      kV: 0.045,
      kA: 0.009,
      kP: 0.3392,
      resistance: 0.3,
      torqueConstant: 0.018,
    },
  },
  projectile: {
    name: "BIOBUZZ POLLEN - Current Robot",
    model: "sphere",
    diameter: 2.8 * inch,
    mass: 0.025,
    inertia: null,
    initialVelocity: 0.5,
    spin: 0,
    roughness: 1,
  },
  aero: {
    cd: 0.47,
    liftSlope: 0.6,
    liftMax: 0.5,
    spinDecay: 0.1,
    magnus: true,
  },
  environment: {
    gravity: 9.80665,
    density: 1.225,
    temperature: 288.15,
    pressure: 101325,
    altitude: 0,
    wind: [0, 0, 0],
  },
  field: fieldConfig,
  simulation: {
    absTolerance: 1e-8,
    relTolerance: 1e-7,
    maxStep: 0.008,
    maxTime: 5,
    maxSpeed: 9,
    minOmega: rpm(300),
    maxOmega: rpm(5000),
    entryMin: deg(5),
    entryMax: deg(90),
    apex: "any",
    apexClearance: 0,
    objective: "energy",
  },
};
export const recalc: Config = structuredClone(current);
recalc.name = "ReCalc Reference - Uploaded Configuration";
Object.assign(recalc.shooter, {
  mode: "recalc",
  topology: "compound",
  primary: wheel(4 * inch, rpm(1700), 0.3, 1.3 * inertiaImperial),
  secondary: {
    ...sushiWheel(0, 0, 0, 0),
    ...wheel(inch, rpm(6800), 0.05, 0),
    ratio: 4,
  },
  rollers: [],
  link: "gear",
  flywheelEnabled: true,
  flywheel: { ...wheel(4 * inch, 0, 0, 0), ratio: 1 },
});
recalc.shooter.motor.name = "2 × REV HD Hex";
recalc.projectile = {
  name: "ReCalc reference projectile",
  model: "sphere",
  diameter: 3.5 * inch,
  mass: 0.042,
  inertia: 0.1 * inertiaImperial,
  initialVelocity: 0.5,
  spin: 0,
  roughness: 1,
};
export const recalcReference = {
  maxAchievableOmega: rpm(2463),
  exitVelocity: 7.585,
  spin: 0,
  energyToBall: 1.208,
  drop: rpm(274),
  postOmega: rpm(1426),
  spinup: 0.323,
  recovery: 0.098,
  kV: 0.045,
  kA: 0.009,
  effectiveInertia: 0.264 * inertiaImperial,
  kP: 0.3392,
};
export const presets = [
  current,
  { ...structuredClone(current), name: "BIOBUZZ POLLEN - Current Robot" },
  recalc,
];
